drop table if exists mlbam_pitchfx;
create table mlbam_pitchfx (
    gid varchar(30) not null, 
    pitch_time timestamp,
    away_team char(3) not null,
    home_team char(3) not null,
    away_team_score smallint not null,
    home_team_score smallint not null,
    seq_num smallint not null,
    ab_num smallint not null,
    pitch_num smallint not null,
    inning smallint not null,
    half_inning smallint not null,
    event_num smallint,
    balls smallint not null,
    strikes smallint not null,
    --outs smallint not null,
    event varchar(50),
    event_description text,

    batter_id integer not null,
    batter_hand char(1),
    batter_height smallint,
    pitcher_id integer not null,
    pitcher_throws char(1),

    init_speed decimal(4,1),
    init_pos_x decimal(4,3),
    init_pos_y decimal(5,3),
    init_pos_z decimal(4,3),
    init_vel_x decimal(5,3),
    init_vel_y decimal(6,3),
    init_vel_z decimal(5,3),
    init_acc_x decimal(5,3),
    init_acc_y decimal(5,3),
    init_acc_z decimal(5,3),
    plate_speed decimal(4,1),
    plate_x decimal(5,2),
    plate_y decimal(5,2),
    plate_z decimal(5,2),
    pfx_x decimal(4,2),
    pfx_y decimal(4,2),
    pfx_z decimal(4,2),
    break_y decimal(3,1),
    break_angle decimal(3,1),
    break_length decimal(3,1),
    strike_zone_top decimal(3,2),
    strike_zone_bottom decimal(3,2),
    pitch_type char(2),
    pitch_name varchar(25),
    pitch_type_confidence decimal(4,3),
    zone smallint,
    nasty smallint,
    spin_dir decimal(6,3),
    spin_rate decimal(7,3),

    pitch_result char(1),
    pitch_result_description varchar(50)
);