
drop table if exists retro_raw_gamelogs;
create table retro_raw_gamelogs (
	date_game char(8) not null,
	game_num char(1) not null,
	day_of_week char(3) null,
	visitor_team_id char(3) null,
	visitor_lg_id char(2) null,
	visitor_game_num smallint null,
	home_team_id char(3) null,
	home_lg_id char(2) null,
	home_game_num smallint null,
	visitor_score smallint null,
	home_score smallint null,
	outs smallint null,
	day_or_night char(1) null,
	completion_info varchar(25),
	forfeit_info char(1),
	protest_info varchar(2),
	park_id char(5),
	attendance integer,
	minutes smallint,
	visitor_line_score varchar(50) null,
	home_line_score varchar(50) null,
	visitor_AB smallint,
	visitor_H smallint,
	visitor_2B smallint,
	visitor_3B smallint,
	visitor_HR smallint,
	visitor_RBI smallint,
	visitor_SH smallint,
	visitor_SF smallint,
	visitor_HBP smallint,
	visitor_BB smallint,
	visitor_IBB smallint,
	visitor_SO smallint,
	visitor_SB smallint,
	visitor_CS smallint,
	visitor_GIDP smallint,
	visitor_CI smallint,
	visitor_LOB smallint,
	visitor_pitchers_used smallint,
    visitor_ER_indiv smallint,
    visitor_ER_team smallint,
    visitor_WP smallint,
    visitor_BK smallint,
    visitor_PO smallint,
    visitor_A smallint,
    visitor_E smallint,
    visitor_PB smallint,
    visitor_DP smallint,
    visitor_TP smallint,
    home_AB smallint,
    home_H smallint,
    home_2B smallint,
    home_3B smallint,
    home_HR smallint,
    home_RBI smallint,
    home_SH smallint,
    home_SF smallint,
    home_HBP smallint,
    home_BB smallint,
    home_IBB smallint,
    home_SO smallint,
    home_SB smallint,
    home_CS smallint,
    home_GIDP smallint,
    home_CI smallint,
    home_LOB smallint,
    home_pitchers_used smallint,
    home_ER_indiv smallint,
    home_ER_team smallint,
    home_WP smallint,
    home_BK smallint,
    home_PO smallint,
    home_A smallint,
    home_E smallint,
    home_PB smallint,
    home_DP smallint,
    home_TP smallint,
    umpire_home_id varchar(9),
    umpire_home_name varchar(50),
    umpire_1B_id varchar(9),
    umpire_1B_name varchar(50),
    umpire_2B_id varchar(9),
    umpire_2B_name varchar(50),
    umpire_3B_id varchar(9),
    umpire_3B_name varchar(50),
    umpire_LF_id varchar(9),
    umpire_LF_name varchar(50),
    umpire_RF_id varchar(9),
    umpire_RF_name varchar(50),
    visitor_manager_id varchar(9),
    visitor_manager_name varchar(50),
    home_manager_id varchar(9),
    home_manager_name varchar(50),
    winning_pitcher_id varchar(9),
    winning_pitcher_name varchar(50),
    losing_pitcher_id varchar(9),
    losing_pitcher_name varchar(50),
    saving_pitcher_id varchar(9),
    saving_pitcher_name varchar(50),
    batting_gwrbi_id varchar(9),
    batting_gwrbi_name varchar(50),
    visitor_pitcher_id varchar(9),
    visitor_pitcher_name varchar(50),
    home_pitcher_id varchar(9),
    home_pitcher_name varchar(50),
    visitor_batter_1_id varchar(9),
    visitor_batter_1_name varchar(50),
    visitor_batter_1_pos smallint,
    visitor_batter_2_id varchar(9),
    visitor_batter_2_name varchar(50),
    visitor_batter_2_pos smallint,
    visitor_batter_3_id varchar(9),
    visitor_batter_3_name varchar(50),
    visitor_batter_3_pos smallint,
    visitor_batter_4_id varchar(9),
    visitor_batter_4_name varchar(50),
    visitor_batter_4_pos smallint,
    visitor_batter_5_id varchar(9),
    visitor_batter_5_name varchar(50),
    visitor_batter_5_pos smallint,
    visitor_batter_6_id varchar(9),
    visitor_batter_6_name varchar(50),
    visitor_batter_6_pos smallint,
    visitor_batter_7_id varchar(9),
    visitor_batter_7_name varchar(50),
    visitor_batter_7_pos smallint,
    visitor_batter_8_id varchar(9),
    visitor_batter_8_name varchar(50),
    visitor_batter_8_pos smallint,
    visitor_batter_9_id varchar(9),
    visitor_batter_9_name varchar(50),
    visitor_batter_9_pos smallint,
    home_batter_1_id varchar(9),
    home_batter_1_name varchar(50),
    home_batter_1_pos smallint,
    home_batter_2_id varchar(9),
    home_batter_2_name varchar(50),
    home_batter_2_pos smallint,
    home_batter_3_id varchar(9),
    home_batter_3_name varchar(50),
    home_batter_3_pos smallint,
    home_batter_4_id varchar(9),
    home_batter_4_name varchar(50),
    home_batter_4_pos smallint,
    home_batter_5_id varchar(9),
    home_batter_5_name varchar(50),
    home_batter_5_pos smallint,
    home_batter_6_id varchar(9),
    home_batter_6_name varchar(50),
    home_batter_6_pos smallint,
    home_batter_7_id varchar(9),
    home_batter_7_name varchar(50),
    home_batter_7_pos smallint,
    home_batter_8_id varchar(9),
    home_batter_8_name varchar(50),
    home_batter_8_pos smallint,
    home_batter_9_id varchar(9),
    home_batter_9_name varchar(50),
    home_batter_9_pos smallint,
    additional_info text,
    acquisition_info char(1)
);


drop table if exists retro_postseason_raw_gamelogs;
create table retro_postseason_raw_gamelogs (like retro_raw_gamelogs);

drop table if exists retro_allstar_raw_gamelogs;
create table retro_allstar_raw_gamelogs (like retro_raw_gamelogs);