 drop table if exists retro_raw_events;
 create table retro_raw_events (
  game_id varchar(12) not null,
  away_team_id varchar(3) not null,
  inn_ct smallint not null,
  bat_home_id smallint not null,
  outs_ct smallint not null,
  balls_ct smallint not null,
  strikes_ct smallint not null,
  pitch_seq_tx varchar(40) null,
  away_score_ct smallint not null,
  home_score_ct smallint not null,
  bat_id varchar(8) not null,
  bat_hand_cd varchar(1) not null,
  resp_bat_id varchar(8) not null,
  resp_bat_hand_cd varchar(1) not null,
  pit_id varchar(8) not null,
  pit_hand_cd varchar(1) not null,
  resp_pit_id varchar(8) not null,
  resp_pit_hand_cd varchar(1) not null,
  pos2_fld_id varchar(8) null,
  pos3_fld_id varchar(8) null,
  pos4_fld_id varchar(8) null,
  pos5_fld_id varchar(8) null,
  pos6_fld_id varchar(8) null,
  pos7_fld_id varchar(8) null,
  pos8_fld_id varchar(8) null,
  pos9_fld_id varchar(8) null,
  base1_run_id varchar(8) null,
  base2_run_id varchar(8) null,
  base3_run_id varchar(8) null,
  event_tx varchar(100) null,
  leadoff_fl varchar(1) null,
  ph_fl varchar(1) null,
  bat_fld_cd smallint null,
  bat_lineup_id smallint null,
  event_cd smallint null,
  bat_event_fl varchar(1) null,
  ab_fl varchar(1) null,
  h_cd smallint null,
  sh_fl varchar(1) null,
  sf_fl varchar(1) null,
  event_outs_ct smallint null,
  dp_fl varchar(1) null,
  tp_fl varchar(1) null,
  rbi_ct smallint null,
  wp_fl varchar(1) null,
  pb_fl varchar(1) null,
  fld_cd smallint null,
  battedball_cd varchar(1) null,
  bunt_fl varchar(1) null,
  foul_fl varchar(1) null,
  battedball_loc_tx varchar(5) null,
  err_ct smallint null,
  err1_fld_cd smallint null,
  err1_cd varchar(1) null,
  err2_fld_cd smallint null,
  err2_cd varchar(1) null,
  err3_fld_cd smallint null,
  err3_cd varchar(1) null,
  bat_dest_id smallint null,
  run1_dest_id smallint null,
  run2_dest_id smallint null,
  run3_dest_id smallint null,
  bat_play_tx varchar(10) null,
  run1_play_tx varchar(15) null,
  run2_play_tx varchar(15) null,
  run3_play_tx varchar(15) null,
  run1_sb_fl varchar(1) null,
  run2_sb_fl varchar(1) null,
  run3_sb_fl varchar(1) null,
  run1_cs_fl varchar(1) null,
  run2_cs_fl varchar(1) null,
  run3_cs_fl varchar(1) null,
  run1_pk_fl varchar(1) null,
  run2_pk_fl varchar(1) null,
  run3_pk_fl varchar(1) null,
  run1_resp_pit_id varchar(8) null,
  run2_resp_pit_id varchar(8) null,
  run3_resp_pit_id varchar(8) null,
  game_new_fl varchar(1) null,
  game_end_fl varchar(1) null,
  pr_run1_fl varchar(1) null,
  pr_run2_fl varchar(1) null,
  pr_run3_fl varchar(1) null,
  removed_for_pr_run1_id varchar(8) null,
  removed_for_pr_run2_id varchar(8) null,
  removed_for_pr_run3_id varchar(8) null,
  removed_for_ph_bat_id varchar(8) null,
  removed_for_ph_bat_fld_cd smallint null,
  po1_fld_cd smallint null,
  po2_fld_cd smallint null,
  po3_fld_cd smallint null,
  ass1_fld_cd smallint null,
  ass2_fld_cd smallint null,
  ass3_fld_cd smallint null,
  ass4_fld_cd smallint null,
  ass5_fld_cd smallint null,
  event_id smallint null,
  home_team_id varchar(3) null,
  bat_team_id varchar(3) null,
  fld_team_id varchar(3) null,
  bat_last_id smallint null,
  inn_new_fl varchar(1) null,
  inn_end_fl varchar(1) null,
  start_bat_score_ct smallint null,
  start_fld_score_ct smallint null,
  inn_runs_ct smallint null,
  game_pa_ct smallint null,
  inn_pa_ct smallint null,
  pa_new_fl varchar(1) null,
  pa_trunc_fl varchar(1) null,
  start_bases_cd smallint null,
  end_bases_cd smallint null,
  bat_start_fl varchar(1) null,
  resp_bat_start_fl varchar(1) null,
  bat_on_deck_id varchar(8),
  bat_in_hold_id varchar(8),
  pit_start_fl varchar(1),
  resp_pit_start_fl varchar(1),
  run1_fld_cd smallint,
  run1_lineup_cd smallint,
  run1_origin_event_id smallint,
  run2_fld_cd smallint,
  run2_lineup_cd smallint,
  run2_origin_event_id smallint,
  run3_fld_cd smallint,
  run3_lineup_cd smallint,
  run3_origin_event_id smallint,
  run1_resp_cat_id varchar(8),
  run2_resp_cat_id varchar(8),
  run3_resp_cat_id varchar(8),
  pa_ball_ct smallint,
  pa_called_ball_ct smallint,
  pa_intent_ball_ct smallint,
  pa_pitchout_ball_ct smallint,
  pa_hitbatter_ball_ct smallint,
  pa_other_ball_ct smallint,
  pa_strike_ct smallint,
  pa_called_strike_ct smallint,
  pa_swingmiss_strike_ct smallint,
  pa_foul_strike_ct smallint,
  pa_inplay_strike_ct smallint,
  pa_other_strike_ct smallint,
  event_runs_ct smallint,
  fld_id varchar(8),
  base2_force_fl varchar(1),
  base3_force_fl varchar(1),
  base4_force_fl varchar(1),
  bat_safe_err_fl varchar(1),
  bat_fate_id smallint,
  run1_fate_id smallint,
  run2_fate_id smallint,
  run3_fate_id smallint,
  fate_runs_ct smallint,
  ass6_fld_cd smallint,
  ass7_fld_cd smallint, 
  ass8_fld_cd smallint,
  ass9_fld_cd smallint,
  ass10_fld_cd smallint,
  unknown_out_exc_fl varchar(1),
  uncertain_play_exc_fl varchar(1),
  primary key (game_id, event_id)
);

drop table if exists retro_postseason_raw_events;
create table retro_postseason_raw_events (like retro_raw_events);

drop table if exists retro_allstar_raw_events;
create table retro_allstar_raw_events (like retro_raw_events);



 