 DROP TABLE IF EXISTS events;
 CREATE TABLE events (
  pbp_id MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  game_id CHAR(12) NOT NULL,
  year_id year(4) NOT NULL,
  away_team_id CHAR(3) NOT NULL,
  inn_ct TINYINT(2) UNSIGNED NOT NULL,
  bat_home_id TINYINT(1) UNSIGNED NOT NULL,
  outs_ct TINYINT(1) UNSIGNED NOT NULL,
  balls_ct TINYINT(1) UNSIGNED NOT NULL,
  strikes_ct TINYINT(1) UNSIGNED NOT NULL,
  pitch_seq_tx VARCHAR(40) NULL,
  away_score_ct TINYINT(2) UNSIGNED NOT NULL,
  home_score_ct TINYINT(2) UNSIGNED NOT NULL,
  bat_id CHAR(8) NOT NULL,
  bat_hand_cd CHAR(1) NOT NULL,
  resp_bat_id CHAR(8) NOT NULL,
  resp_bat_hand_cd CHAR(1) NOT NULL,
  pit_id CHAR(8) NOT NULL,
  pit_hand_cd CHAR(1) NOT NULL,
  resp_pit_id CHAR(8) NOT NULL,
  resp_pit_hand_cd CHAR(1) NOT NULL,
  pos2_fld_id CHAR(8) NULL,
  pos3_fld_id CHAR(8) NULL,
  pos4_fld_id CHAR(8) NULL,
  pos5_fld_id CHAR(8) NULL,
  pos6_fld_id CHAR(8) NULL,
  pos7_fld_id CHAR(8) NULL,
  pos8_fld_id CHAR(8) NULL,
  pos9_fld_id CHAR(8) NULL,
  base1_run_id VARCHAR(8) NULL,
  base2_run_id VARCHAR(8) NULL,
  base3_run_id VARCHAR(8) NULL,
  event_tx VARCHAR(100) NULL,
  leadoff_fl CHAR(1) NULL,
  ph_fl CHAR(1) NULL,
  bat_fld_cd TINYINT(1) UNSIGNED NULL,
  bat_lineup_id TINYINT(2) UNSIGNED NULL,
  event_cd TINYINT(2) UNSIGNED NULL,
  bat_event_fl CHAR(1) NULL,
  ab_fl CHAR(1) NULL,
  h_cd TINYINT(1) UNSIGNED NULL,
  sh_fl CHAR(1) NULL,
  sf_fl CHAR(1) NULL,
  event_outs_ct TINYINT(1) UNSIGNED NULL,
  dp_fl CHAR(1) NULL,
  tp_fl CHAR(1) NULL,
  rbi_ct TINYINT(1) UNSIGNED NULL,
  wp_fl CHAR(1) NULL,
  pb_fl CHAR(1) NULL,
  fld_cd TINYINT(2) UNSIGNED NULL,
  battedball_cd CHAR(1) NULL,
  bunt_fl CHAR(1) NULL,
  foul_fl CHAR(1) NULL,
  battedball_loc_tx VARCHAR(5) NULL,
  err_ct TINYINT(1) UNSIGNED NULL,
  err1_fld_cd TINYINT(2) UNSIGNED NULL,
  err1_cd CHAR(1) NULL,
  err2_fld_cd TINYINT(2) UNSIGNED NULL,
  err2_cd CHAR(1) NULL,
  err3_fld_cd TINYINT(2) UNSIGNED NULL,
  err3_cd CHAR(1) NULL,
  bat_dest_id TINYINT(1) UNSIGNED NULL,
  run1_dest_id TINYINT(1) UNSIGNED NULL,
  run2_dest_id TINYINT(1) UNSIGNED NULL,
  run3_dest_id TINYINT(1) UNSIGNED NULL,
  bat_play_tx VARCHAR(8) NULL,
  run1_play_tx VARCHAR(15) NULL,
  run2_play_tx VARCHAR(15) NULL,
  run3_play_tx VARCHAR(15) NULL,
  run1_sb_fl CHAR(1) NULL,
  run2_sb_fl CHAR(1) NULL,
  run3_sb_fl CHAR(1) NULL,
  run1_cs_fl CHAR(1) NULL,
  run2_cs_fl CHAR(1) NULL,
  run3_cs_fl CHAR(1) NULL,
  run1_pk_fl CHAR(1) NULL,
  run2_pk_fl CHAR(1) NULL,
  run3_pk_fl CHAR(1) NULL,
  run1_resp_pit_id VARCHAR(8) NULL,
  run2_resp_pit_id VARCHAR(8) NULL,
  run3_resp_pit_id VARCHAR(8) NULL,
  game_new_fl CHAR(1) NULL,
  game_end_fl CHAR(1) NULL,
  pr_run1_fl CHAR(1) NULL,
  pr_run2_fl CHAR(1) NULL,
  pr_run3_fl CHAR(1) NULL,
  removed_for_pr_run1_id VARCHAR(8) NULL,
  removed_for_pr_run2_id VARCHAR(8) NULL,
  removed_for_pr_run3_id VARCHAR(8) NULL,
  removed_for_ph_bat_id VARCHAR(8) NULL,
  removed_for_ph_bat_fld_cd TINYINT(2) UNSIGNED NULL,
  po1_fld_cd TINYINT(2) UNSIGNED NULL,
  po2_fld_cd TINYINT(2) UNSIGNED NULL,
  po3_fld_cd TINYINT(2) UNSIGNED NULL,
  ass1_fld_cd TINYINT(2) UNSIGNED NULL,
  ass2_fld_cd TINYINT(2) UNSIGNED NULL,
  ass3_fld_cd TINYINT(2) UNSIGNED NULL,
  ass4_fld_cd TINYINT(2) UNSIGNED NULL,
  ass5_fld_cd TINYINT(2) UNSIGNED NULL,
  event_id TINYINT(3) UNSIGNED NULL,
  home_team_id CHAR(3) NULL,
  bat_team_id CHAR(3) NULL,
  fld_team_id CHAR(3) NULL,
  bat_last_id TINYINT(1) UNSIGNED NULL,
  inn_new_fl CHAR(1) NULL,
  inn_end_fl CHAR(1) NULL,
  start_bat_score_ct TINYINT(2) UNSIGNED NULL,
  start_fld_score_ct TINYINT(2) UNSIGNED NULL,
  inn_runs_ct TINYINT(2) UNSIGNED NULL,
  game_pa_ct TINYINT(3) UNSIGNED NULL,
  inn_pa_ct TINYINT(2) UNSIGNED NULL,
  pa_new_fl CHAR(1) NULL,
  pa_trunc_fl CHAR(1) NULL,
  start_bases_cd TINYINT(1) UNSIGNED NULL,
  end_bases_cd TINYINT(1) UNSIGNED NULL,
  bat_start_fl CHAR(1) NULL,
  resp_bat_start_fl CHAR(1) NULL,
  bat_on_deck_id VARCHAR(8),
  bat_in_hold_id VARCHAR(8),
  pit_start_fl CHAR(1),
  resp_pit_start_fl CHAR(1),
  run1_fld_cd TINYINT(2) UNSIGNED,
  run1_lineup_cd TINYINT(2) UNSIGNED,
  run1_origin_event_id TINYINT(2) UNSIGNED,
  run2_fld_cd TINYINT(2) UNSIGNED,
  run2_lineup_cd TINYINT(2) UNSIGNED,
  run2_origin_event_id TINYINT(2) UNSIGNED,
  run3_fld_cd TINYINT(2) UNSIGNED,
  run3_lineup_cd TINYINT(2) UNSIGNED,
  run3_origin_event_id TINYINT(2) UNSIGNED,
  run1_resp_cat_id VARCHAR(8) ,
  run2_resp_cat_id VARCHAR(8) ,
  run3_resp_cat_id VARCHAR(8) ,
  pa_ball_ct TINYINT(1) UNSIGNED,
  pa_called_ball_ct TINYINT(1) UNSIGNED,
  pa_intent_ball_ct TINYINT(1) UNSIGNED,
  pa_pitchout_ball_ct TINYINT(1) UNSIGNED,
  pa_hitbatter_ball_ct TINYINT(1) UNSIGNED,
  pa_other_ball_ct TINYINT(1) UNSIGNED,
  pa_strike_ct TINYINT(1) UNSIGNED,
  pa_called_strike_ct TINYINT(1) UNSIGNED,
  pa_swingmiss_strike_ct TINYINT(1) UNSIGNED,
  pa_foul_strike_ct TINYINT(1) UNSIGNED,
  pa_inplay_strike_ct TINYINT(1) UNSIGNED,
  pa_other_strike_ct TINYINT(1) UNSIGNED,
  event_runs_ct TINYINT(1) UNSIGNED,
  fld_id VARCHAR(8),
  base2_force_fl CHAR(1) ,
  base3_force_fl CHAR(1) ,
  base4_force_fl CHAR(1) ,
  bat_safe_err_fl CHAR(1) ,
  bat_fate_id TINYINT(1) UNSIGNED,
  run1_fate_id TINYINT(1) UNSIGNED,
  run2_fate_id TINYINT(1) UNSIGNED,
  run3_fate_id TINYINT(1) UNSIGNED,
  fate_runs_ct TINYINT(1) UNSIGNED,
  ass6_fld_cd TINYINT(1) UNSIGNED,
  ass7_fld_cd TINYINT(1) UNSIGNED, 
  ass8_fld_cd TINYINT(1) UNSIGNED,
  ass9_fld_cd TINYINT(1) UNSIGNED,
  ass10_fld_cd TINYINT(1) UNSIGNED,
  unknown_out_exc_fl VARCHAR(1),
  uncertain_play_exc_fl VARCHAR(1),
  KEY events_gameid_idx (GAME_ID),
  INDEX events_year_idx (YEAR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ;

